# Monthly profitability checker configuration
monthlyProfitability:
  enabled: true
  schedule: "*/45 * * * *" # Run every 30 seconds
  config:
    voteAccount: "sT34kbaqmHWbPwjhyeG1GnjoX82KpXawFsnzUkzJpYX" # Your vote account public key
    identity: "5t4shVsKnUqgjmhK3fFNsvyju2E6Rd7cc4S5pmqqEVEW" # Your validator identity public key
    monthlyExpenses: "2400" # Monthly expenses in USD
    monthlyBillingDay: 19 # Day of month to start tracking from
    voteCostReimbursement: 75 # Vote cost reimbursement in USD

# SFDP compliance checker
sfdpCompliance:
  enabled: true
  schedule: "*/30 * * * *" # Run every 30 seconds
  config:
    mainnetIdentity: "5t4shVsKnUqgjmhK3fFNsvyju2E6Rd7cc4S5pmqqEVEW" # Your mainnet validator identity
    testnetIdentity: "96cYajmkUBpEw5HFs5MQDbr6BngPMgUb34JkLorRZTdS" # Your testnet validator identity
    onlyLogIssues: true
